header:
  version: 12
  includes:
    - repo: mapio-manifest
      file: base.yml
    - repo: mapio-manifest
      file: mapio-prod.yml

repos:
  mapio-manifest:
    url: "git@github.com:pcurt/mapio-manifest.git"
    refspec: main
    layers: 
      .: excluded
